server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # Ce serveur ne s'enregistre pas lui-même
    fetch-registry: false          # Pas besoin de récupérer le registre
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0    # Démarrage plus rapide en dev
    enable-self-preservation: false        # Désactiver la self-preservation en dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
