name: mobile_app
description: Application mobile Flutter — Gestion des Étudiants
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  # Client HTTP pour consommer l'API REST
  http: ^1.2.0

flutter:
  uses-material-design: true
